# https://gohugo.io/getting-started/configuration/#all-configuration-settings

# Slash works for both development and production.
baseURL: '/'
title: 'Ryo & Ayami'
languageCode: ja
defaultContentLanguage: ja
enableRobotsTXT: true
hasCJKLanguage: true

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  description: the blog of Ryo and Ayami

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: home
      name: Home
      url: '/'
      weight: 1
    - identifier: ryo
      name: Ryo
      url: '/ryo/'
      weight: 2
    - identifier: ayami
      name: Ayami
      url: '/ayami/'
      weight: 3

# https://gohugo.io/content-management/taxonomies/
taxonomies:
  tag: tags
