# Available options: https://www.netlifycms.org/docs/configuration-options/
# Example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
backend:
  name: git-gateway
  # git Gateway Error: Please ask your site administrator to reissue the Git Gateway token
  # https://community.netlify.com/t/git-gateway-error/12220/8
  repo: mnishiguchi/ryoayami
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

# https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: content/images

public_folder: /images

site_url: https://ryoayami.com
logo_url: https://user-images.githubusercontent.com/7563926/163997976-f10f5c94-14c2-463e-a996-f09dd139f691.png
locale: 'ja'
show_preview_links: false

collections:
  - name: pages
    label: ページ
    editor:
      preview: false
    files:
      - file: 'content/_index.md'
        label: Home
        name: home
        fields:
          - label: 'identifier'
            name: 'identifier'
            widget: 'hidden'
            default: 'home'
          - label: 本文
            name: body
            widget: markdown
          - label: 写真A
            name: image_a
            widget: image
          - label: 写真B
            name: image_b
            widget: image
          - label: 写真C
            name: image_c
            widget: image
      - file: 'content/ryo/_index.md'
        label: 遼のメイン
        name: ryo_section
        fields:
          - label: 'identifier'
            name: 'identifier'
            widget: 'hidden'
            default: 'ryo_section'
          - label: 本文
            name: body
            widget: markdown
      - file: 'content/ayami/_index.md'
        label: 彩未のメイン
        name: ayami_section
        fields:
          - label: 'identifier'
            name: 'identifier'
            widget: 'hidden'
            default: 'ayami_section'
          - label: 本文
            name: body
            widget: markdown
      - file: 'content/about.md'
        label: About
        name: about
        fields:
          - label: 'identifier'
            name: 'identifier'
            widget: 'hidden'
            default: 'about'
          - label: 本文
            name: body
            widget: markdown
  - name: 'ryo'
    label: '遼の記事'
    folder: 'content/ryo'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'identifier'
        name: 'identifier'
        widget: 'hidden'
        default: 'ryo_article'
      - label: 題目
        name: 'title'
        widget: 'string'
      - label: 日付
        name: 'date'
        widget: 'date'
      - label: 本文
        name: 'body'
        widget: 'markdown'
      - label: タグ
        name: 'tags'
        widget: 'list'
        required: false
        field: { label: Name, name: name, widget: string }
    filter: { field: 'identifier', value: 'ryo_article' }
    sortable_fields: ['date', 'title']
  - name: 'ayami'
    label: '彩未の記事'
    folder: 'content/ayami'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'identifier'
        name: 'identifier'
        widget: 'hidden'
        default: 'ayami_article'
      - label: 題目
        name: 'title'
        widget: 'string'
      - label: 日付
        name: 'date'
        widget: 'date'
      - label: 本文
        name: 'body'
        widget: 'markdown'
      - label: タグ
        name: 'tags'
        widget: 'list'
        required: false
        field: { label: Name, name: name, widget: string }
    filter: { field: 'identifier', value: 'ayami_article' }
    sortable_fields: ['date', 'title']
